name: ğŸš€ Deploy
on:
  push:
    branches: [ "tugas4-bonus" ]
jobs:
  deploy-cpanel:
    name: ğŸš€ Deploy to CPanel
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get Latest Code
        uses: actions/checkout@v4.1.2

      - name: âš™ï¸ Use PHP 8.2
        uses: shivammathur/setup-php@main
        with:
          php-version: "8.2"

      - name: âš™ï¸ Use NodeJS 20
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "20"

      - name: ğŸ”¨ Install Dependencies PHP
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: ğŸ”¨ Install Dependencies JS
        run: npm install

      - name: ğŸ—„ï¸ Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: ğŸš€ Deploy to CPanel
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME2 }}
          FTP_PASSWORD: ${{ secrets.FTP_PASS }}
        run: npm run deploy
