on:
  push:
    branches: [ tugas2-backend ]
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ‰ Auto Deploy
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [20.16, 21.7, 22.5]
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v4

    # - name: Use Node.js 22.5
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: '22.5'
    #     cache: 'npm'

    # check php version
    - name: ğŸ˜ Check PHP version
      run: php -v

        # composer install
    - name: ğŸ“¦ Install Composer
      run: composer update

      # cp .env.example .env
    - name: ğŸ›  Copy .env
      run: cp .env.example .env

      # key generate
    - name: ğŸ”‘ Generate key
      run: php artisan key:generate

      # migrate
    # - name: ğŸš€ Migrate & ğŸŒ± Seed
    #   run: php artisan migrate:fresh --seed

    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME2 }}
        password: ${{ secrets.FTP_PASS }}
        protocol: ftps
        port: ${{ secrets.FTP_PORT }}
        exclude: |
          **/.git*
          **/.git*/**
